version = 1

[[annotations]]
path = [
    "*.html",
    "styles/*",
]
SPDX-FileCopyrightText = "© 2025 Functional Software, Inc. d/b/a Sentry"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "images/*",
]
SPDX-FileCopyrightText = "© 2024 Functional Software, Inc. d/b/a Sentry"
SPDX-License-Identifier = "LicenseRef-Restricted"

[[annotations]]
path = [
    "fonts/azaret-mono*",
    "fonts/AzeretMono*",
]
SPDX-FileCopyrightText = "Copyright 2021 The Azeret Project Authors (https://github.com/displaay/azeret)"
SPDX-License-Identifier = "OFL-1.1"


[[annotations]]
path = [
    "fonts/libre-franklin*",
    "fonts/LibreFranklin*",
]
SPDX-FileCopyrightText = "Copyright (c) 2015, Impallari Type (www.impallari.com)"
SPDX-License-Identifier = "OFL-1.1"
